In [ ]:
import numpy as np
# 1 Write a program to create a 5 dimensional array with all zeros and ones


In [23]:
arr1=np.zeros((1,1,1,1,7))
arr2=np.ones((1,1,1,1,3))
print(arr1)
print(arr2)

[[[[[0. 0. 0. 0. 0. 0. 0.]]]]]
[[[[[1. 1. 1.]]]]]


In [24]:
# 2 Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [39]:
arr1=np.array([[np.zeros(10,)],[np.ones(10,)],[np.full((10,),5)]])
print(arr1)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]]


In [40]:
# 3 Write a program to create a 3x4 matrix filled with values from 10 to 21.


In [42]:
arr1=np.arange(10,22).reshape(3,4)
print(arr1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [43]:
# 4 Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [45]:
arr1=np.diag(range(10))
print(arr1)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


In [46]:
# 5 Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [49]:
arr1=np.arange(1,17).reshape(4,4)
print(arr1)
arr1[:,::-1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [50]:
#6 Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]

In [56]:
arr1=np.arange(12,28)
arr1[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [57]:
# 7 Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [60]:
arr1=np.arange(1,101).reshape(10,10)
arr1[(arr1>30) & (arr1<80) & (arr1%5==0)]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [61]:
# 8 Write a program to create a 2D array with 1 on the border and 0 inside.


In [70]:
arr1=np.ones((5,5))
arr1[1:-1,1:-1]=0
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
# 9 Write a program to create a checkerboard pattern .Don't use default array function
#Checkerboard pattern:                                                   
#[[0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]    

In [77]:
arr1=np.zeros((8,8))
arr1[::2,1::2]=1
arr1[1::2,::2]=1
arr1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
# 10 Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]

In [82]:
arr1=np.array([10,20,30,40])
arr2=np.array([10,30,40,50])
l=[]
for i in arr1:
    for j in arr2:
        if i==j:
            if i in l:
                continue
            else:
                l.append(i)
print("common values between two arrays:",l)

common values between two arrays: [10, 30, 40]


In [83]:
# 11 Write a program to create an array 2d array and then reshape into 1d array

In [87]:
arr1=np.eye(4)
print(arr1)
arr2=arr1.reshape(16,)
arr2

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [89]:
# 12 Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [ ]:
dim=input("Enter your array dimension 1d or 2d:")
s=0
c=0
f=0
if dim.lower()=="1d":
    l=[]
    shape=int(input("Enter number of elements:"))
    for i in range(shape):
        elem_type=input("Enter datatype of element int float complex str:")
        if elem_type.lower()=="int":
            elem=int(input("Enter a number:"))
            l.append(elem)
        elif elem_type.lower()=="float":
            elem=float(input("Enter a float number:"))
            l.append(elem)
            f=f+1
        elif elem_type.lower()=="complex":
            elem=complex(input("Enter a complex number:"))
            l.append(elem)
            c=c+1
        elif elem_type.lower()=="str":
            elem=input("Enter a string:")
            l.append(elem)
            s=s+1
        else:
            print("Please check the data type of element you have given:")
    if s>=1:
        for i in l:
            l[l.index(i)]=str(i)
    elif c>=1:
        for i in l:
            l[l.index(i)]=complex(i)
    elif f>=1:
        for i in l:
            l[l.index(i)]=float(i)
    else:
        pass
elif dim.lower()=="2d":
    row=int(input("Enter number of rows:"))
    col=int(input("Enter number of columns"))
    l=[]
    for i in range(row):
        l1=[]
        for j in range(col):
            elem_type=input("Enter datatype of element int float complex str:")
            if elem_type.lower()=="int":
                elem=int(input("Enter a number:"))
                l1.append(elem)
            elif elem_type.lower()=="float":
                elem=float(input("Enter a float number:"))
                l1.append(elem)
                f=f+1
            elif elem_type.lower()=="complex":
                elem=complex(input("Enter a complex number:"))
                l1.append(elem)
                c=c+1
            elif elem_type.lower()=="str":
                elem=input("Enter a string:")
                l1.append(elem)
                s=s+1
            else:
                print("Please check the data type of element you have given:")
        l.append(l1)
    if s>=1:
        for i in range(row):
            for j in range(col):
                l[i][j]=str(l[i][j])
    elif c>=1:
        for i in range(row):
            for j in range(col):
                l[i][j]=complex(l[i][j])
    elif f>=1:
        for i in range(row):
            for j in range(col):
                l[i][j]=float(l[i][j])
    else:
        pass
else:
    print("Give 1d or 2d only")
print(l)