In [1]:
import numpy as np

In [23]:
tips=np.genfromtxt("C:\\Users\\DELL\\Downloads\\tipsf.csv",delimiter=",",skip_header=1)

In [24]:
tips

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [1]:
# 1.What is the total bill value

In [37]:
total_bill=np.sum(tips[:,1])
print(total_bill)

4827.77


In [2]:
# 2.what is the total tip value

In [40]:
total_tip=np.sum(tips[:,2])
print(total_tip)

731.5799999999999


In [3]:
# 3 count how many sun sat thu fri are there

In [52]:
un=np.unique(tips[:,5],return_counts=True)
count=un[1]
print("sunday count",count[1])
print("saturday count",count[0])
print("thursday count",count[2])
print("Friday count",count[3])

sunday count 76
saturday count 87
thursday count 62
Friday count 19


In [4]:
# 4 How many smokers are there

In [105]:
smokers=tips[:,4][tips[:,4]==1]
print("Smokers",len(smokers))

Smokers 93


In [5]:
# 5 what is the average tip given by female and male

In [72]:
f=tips[:,2][tips[:,3]==1]
m=tips[:,2][tips[:,3]==0]
tipf=0
tipm=0
for i in f:
    tipf=tipf+i
for j in m:
    tipm=tipm+j
print("Average Tip given by female:",tipf/len(f))
print("Average Tip given by male",tipm/len(m))

Average Tip given by female: 3.0896178343949052
Average Tip given by male 2.833448275862069


In [6]:
# 6 how much amount is spent by female and male

In [74]:
f=tips[:,1][tips[:,3]==1]
m=tips[:,1][tips[:,3]==0]
billf=0
billm=0
for i in f:
    billf=billf+i
for j in m:
    billm=billm+j
print("Amount spent by female",billf)
print("Amount spent by male",billm)

Amount spent by female 3256.8200000000024
Amount spent by male 1570.9499999999998


In [7]:
# 7 what is the min and max tip given

In [76]:
min_tip=min(tips[:,2])
max_tip=max(tips[:,2])
print("Minimum tip given",min_tip)
print("Maximum tip given",max_tip)

Minimum tip given 1.0
Maximum tip given 10.0


In [8]:
# 8 how many females and males are going for dinner and lunch


In [103]:
lunch=tips[:,3][tips[:,6]==1]
dinner=tips[:,3][tips[:,6]==0]
print("Lunch",len(lunch))
print("Dinner",len(dinner))

Lunch 68
Dinner 176


In [9]:
# 9 find out the average size

In [83]:
size=0
for i in tips[:,-1]:
    size=size+i
avg_size=size/len(tips[:,-1])
print("Average size",avg_size)

Average size 2.569672131147541


In [10]:
# 10 How many female smokers are there and male smokers are there

In [102]:
f=tips[:,4][(tips[:,4]==1) & (tips[:,3]==1)]
m=tips[:,4][(tips[:,4]==1) & (tips[:,3]==0)]
print("Female Smokers",len(f))
print("Male Smokers",len(m))

Female Smokers 60
Male Smokers 33


In [111]:
train=np.genfromtxt("C:\\Users\\DELL\\Downloads\\train_extended.csv",delimiter=",",skip_header=1)
train

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [11]:
# 1 what is max and min length

In [112]:
maximum=max(train[:,0])
minimum=min(train[:,0])
print("Maximum",maximum)
print("Minimum",minimum)

Maximum 7.58349125
Minimum 0.0


In [12]:
# 2 find the difference between min and max length

In [115]:
diff=maximum-minimum
print(diff)

7.58349125


In [13]:
# 3  find columnwise average

In [119]:
def average(x):
    sum=0
    for i in x:
        sum=sum+i
    avg=sum/len(x)
    return avg
np.apply_along_axis(average,0,train)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

In [14]:
# 4 Find out all the age whose height is >0.4

In [122]:
age=train[:,-1][train[:,2]>0.4]
print(age)

[11. 14. 13. ... 11. 11. 11.]


In [15]:
# 5 Find out average height and weight of the persons whose age is 10

In [124]:
height=train[:,2][train[:,-1]==10]
weight=train[:,3][train[:,-1]==10]
h=0
w=0
for i in height:
    h=h+i
for j in weight:
    w=w+i
avg_height=h/len(height)
avg_weight=w/len(weight)
print("Average height of the persons whose age is 10",avg_height)
print("Average weight of the persons whose age is 10",avg_weight)

Average height of the persons whose age is 10 0.3833672856540043
Average weight of the persons whose age is 10 0.3875000000001401


In [16]:
# 6 what is the total shell weight

In [126]:
total_shellw=0
for i in train[:,-2]:
    total_shellw=total_shellw+i
print("Total Shell weight",total_shellw)

Total Shell weight 1326845.8295212665


In [17]:
# 7 How many persons belongs to each and every unique age

In [133]:
unique_age=np.unique(train[:,-1],return_counts=True)
count=unique_age[1]
print("persons unique age",unique_age[0])
print("persons belong to each and every unique age",count)

persons unique age [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 29.]
persons belong to each and every unique age [   46    42   625  2787  5475 12450 18276 26818 32906 30803 23457 12717
 10037  6352  4831  3191  2705  1953  1591  1206   721   296   352   110
    51    46    99    57]


In [18]:
# 8 what is the difference between shucked weight and viscua weight

In [135]:
shu_weight=0
vis_weight=0
for i in train[:,4]:
    shu_weight=shu_weight+i
for j in train[:,5]:
    vis_weight=vis_weight+j
diff=shu_weight-vis_weight
print("Difference between shucked weight and viscua weight",diff)

Difference between shucked weight and viscua weight 999237.8582597616


In [19]:
# 9 what is the average height of the persons whose age between is 14 & 19

In [137]:
height=train[:,2][(train[:,-1]>14) & (train[:,-1]<19)]
h=0
for i in height:
    h=h+i
avg_height=h/len(height)
print("Average height of the persons whose age between is 14 & 19",avg_height)

Average height of the persons whose age between is 14 & 19 0.4190701892744539


In [20]:
# 10 what is the average weight if we include shucked weight,viscera weight and shell weight

In [139]:
total_weight=train[:,3]+train[:,4]+train[:,5]+train[:,6]
tw=0
for i in total_weight:
    tw=tw+i
avg_weight=tw/len(total_weight)
print("Average weight after including shucked weight,viscera weight and shell weight",avg_weight)

Average weight after including shucked weight,viscera weight and shell weight 44.7402166653875
